<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.pentaho.di.plugins</groupId>
    <artifactId>pentaho-reporting-assemblies</artifactId>
    <version>9.3.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>pentaho-reporting-impl-plugin</artifactId>
  <version>9.3.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <pentaho-reporting.version>9.3.0.0-SNAPSHOT</pentaho-reporting.version>
    <project.revision>9.3.0.0-SNAPSHOT</project.revision>
    <resources.directory>${project.basedir}/src/main/resources</resources.directory>
    <assembly.dir>${project.build.directory}/assembly</assembly.dir>
  </properties>

  <name>Pentaho Reporting Impl Plugin Distribution</name>

  <dependencies>
    <dependency>
      <groupId>org.pentaho.di.plugins</groupId>
      <artifactId>pentaho-reporting-impl</artifactId>
      <version>${project.revision}</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
   <build>
    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>add-libs</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${assembly.dir}/lib</outputDirectory>
              <includeScope>compile</includeScope>
              <excludeArtifactIds>pentaho-reporting-impl-plugin</excludeArtifactIds>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>


